In [2]:
import numpy as np

In [4]:
# print the numpy version and the configuration

print(np.__version__)
# np.show_config()

1.20.3


In [6]:
# create a null vector of size 10

Z = np.zeros(10)
Z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
Z = np.zeros(10,dtype=int)
Z

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
# create a null vector of size 10 but the fifth value which is 1

Z = np.zeros(10)
Z[4]=1
Z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [18]:
# Create a vector with values ranging from 10 to 49
Z = np.arange(10,50)
Z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [19]:
# Reverse a vector ( first element become last)
Z= np.arange(11)
Z=Z[::-1]
Z

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [20]:
# Create a 3x3 matrix with values ranging from 0 to 8

Z = np.arange(9).reshape(3,3)
Z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [29]:
# Find indices of non­zero elements from [1,2,0,0,4,0
nz= np.nonzero([1,2,0,0,4,0])
nz

(array([0, 1, 4], dtype=int64),)

In [30]:
# eye diagonal element are 1's and other are zeros
# create a 3x3 identity matrix
Z = np.eye(3)
Z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
# Create a 3x3x3 array with random values
import random as rd

Z= np.random.random((3,3,3))
Z

array([[[0.39804046, 0.35033763, 0.84353261],
        [0.35317719, 0.7670609 , 0.19743634],
        [0.13247978, 0.75485067, 0.5487674 ]],

       [[0.39584338, 0.88382041, 0.78109581],
        [0.39803249, 0.55998942, 0.97379699],
        [0.45569595, 0.4162183 , 0.98013761]],

       [[0.51032862, 0.48667724, 0.58796167],
        [0.16017146, 0.07167177, 0.25339921],
        [0.09384877, 0.10585533, 0.42443129]]])

In [7]:
# Create a 10x10 array with random values and find the minimum & maximum
Z = np.random.random((10,10))
print(np.min(Z))
print(np.max(Z))
# Z
print(Z.min())
print(Z.max())

0.009407747824561108
0.9919543398011684
0.009407747824561108
0.9919543398011684


In [8]:
# . Create a random vector of size 30 and find the mean value
arr= np.random.random(30)
arr.mean()

0.49866721162243893

In [12]:
# 4. Create a 2d array with 1 on the border and 0 inside
Z=np.ones((10,10))
Z[1:-1,1:-1]=0
Z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [15]:
# What is the result of the following expression?
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

False

**diag** 
Extract a diagonal or construct a diagonal array

In [17]:
# Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

Z = np.diag(1+np.arange(4),k=-1)
Z

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [22]:
#  Create a 8x8 matrix and fill it with a checkerboard pattern

Z = np.zeros((8,8), dtype=int)
Z[1::2, ::2]=1
Z[::2, 1::2]=1
Z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [23]:
# Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element